name: Install Nix and setup cache
inputs:
  key:
    description: Key to actions/cache
    required: true
    default: nix-action
  debug:
    description: Enable debug
    required: false
    default: false
  login_with_age:
    description: Debug login with age
    required: false
    default: true
  credential:
    description: Debug credential
    required: false
    default: ""
runs:
  using: composite
  steps:
  - name: Disable MDS service on macOS
    if: ${{ runner.os == 'macOS' }}
    shell: bash
    run: |
      sudo launchctl unload -w /System/Library/LaunchDaemons/com.apple.metadata.mds.plist || true
  - uses: nixbuild/nix-quick-install-action@v26
    with:
      nix_conf: |
        keep-derivations = true
        keep-outputs = true
  - name: Pre cache restore
    shell: bash
    env:
      CACHE_KEY: ${{ inputs.key }}
    run: ${{ github.action_path }}/pre-restore.sh
  - uses: actions/cache/restore@v3
    with:
      key: ${{ env.CACHE_KEY }}-${{ runner.os }}-${{ env.CACHE_TIMESTAMP }}
      restore-keys: |
        ${{ env.CACHE_KEY }}-${{ runner.os }}
      path: |
        /nix/store
        /nix/var/nix/db/db.sqlite
  - name: Post cache restore
    shell: bash
    run: ${{ github.action_path }}/post-restore.sh
  - name: Debug
    if: ${{ inputs.debug == true || inputs.debug == 'true' }}
    shell: bash
    env:
      TTYD_LOGIN_WITH_AGE: ${{ inputs.login_with_age }}
      TTYD_CREDENTIAL: ${{ inputs.credential }}
    run: ${{ github.action_path }}/debug.sh
