name: Install Nix and setup cache (post actions)
inputs:
  gc:
    description: Nix GC
    required: false
    default: false
runs:
  using: composite
  steps:
  - name: Nix GC
    if: ${{ env.CACHE_NEED_UPDATE == 'yes' || inputs.gc == true || inputs.gc == 'true' }}
    shell: bash
    run: |
      # Nix GC
      # create gcroots for flake inputs to prevent gc
      flake_inputs=$(nix flake archive --json --no-write-lock-file)
      while [[ $flake_inputs =~ /nix/store/[^\"]+ ]]
      do
        store_path="${BASH_REMATCH[0]}"
        nix build --out-link "/tmp/${store_path##*/}" "$store_path"
        flake_inputs="${flake_inputs/${store_path}/}"
      done
      nix-store --gc --print-roots --verbose
  - uses: actions/cache/save@v3
    if: ${{ env.CACHE_NEED_UPDATE == 'yes' }}
    with:
      key: ${{ env.CACHE_KEY }}-${{ runner.os }}-${{ env.CACHE_TIMESTAMP }}
      path: |
        /nix/store
        /nix/var/nix/db/db.sqlite
