name: Install Nix and setup cache
inputs:
  key:
    description: Key to actions/cache
    required: true
    default: nix-action
  debug:
    description: Enable debug
    required: false
    default: false
  credential:
    description: Debug credential
    required: false
    default: ""
runs:
  using: composite
  steps:
  - uses: nixbuild/nix-quick-install-action@v26
    with:
      nix_conf: |
        accept-flake-config = true
        experimental-features = nix-command flakes
        keep-derivations = true
        keep-outputs = true
  - name: Pre cache restore
    shell: bash
    env:
      CACHE_KEY: ${{ inputs.key }}
    run: ${{ github.action_path }}/pre-restore.sh
  - uses: actions/cache/restore@v3
    with:
      key: ${{ env.CACHE_KEY }}-${{ runner.os }}-${{ env.CACHE_TIMESTAMP }}
      restore-keys: |
        ${{ env.CACHE_KEY }}-${{ runner.os }}
      path: |
        /nix/store
        /nix/var/nix/db/db.sqlite
  - name: Post cache restore
    shell: bash
    run: ${{ github.action_path }}/post-restore.sh
  - name: Debug
    if: ${{ (inputs.debug == true || inputs.debug == 'true') && inputs.credential != '' }}
    shell: bash
    env:
      TTYD_CREDENTIAL: ${{ inputs.credential }}
    run: ${{ github.action_path }}/debug.sh
