name: Test
permissions: {}
on:
  pull_request:
    paths-ignore:
    - '**.md'
  push:
    paths-ignore:
    - '**.md'
  workflow_dispatch:
    inputs:
      debug:
        description: Enable debug
        type: boolean
        required: false
        default: false
      os:
        description: Debug OS
        required: true
        type: choice
        options: [ubuntu-latest, macos-latest, all]
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - uses: azuwis/nix-action@main
      with:
        key: nix-action-${{ hashFiles('flake.*') }}
        debug: ${{ github.event_name == 'workflow_dispatch' && inputs.debug && (inputs.os == 'all'|| inputs.os == matrix.os) }}
        credential: ${{ secrets.TTYD_CREDENTIAL }}
    - name: Build
      run: |
        nix -L build .#
    - uses: azuwis/nix-action@post
